import crypto from "node:crypto";
type In="DETECTED"|"RECEIVED"|"SCREENING"|"AWAITING_SCREENING"|"AVAILABLE"|"QUARANTINED"; type Out="ACCEPTED"|"RESERVED"|"SCREENING"|"TRAVEL_RULE"|"SIMULATING"|"AWAITING_APPROVAL"|"APPROVED"|"SIGNED"|"BROADCAST"|"SETTLED"|"HELD_FOR_CASE";
const g=globalThis as any; const now=()=>new Date().toISOString(); const id=(p:string)=>p+"_"+crypto.randomBytes(4).toString("hex"); const h=(s:string)=>crypto.createHash("sha256").update(s).digest("hex"); const addr=(s:string)=>"0x"+h(s).slice(0,40);
function fresh(){const s:any={rail:"RUNNING",block:1842931,inbound:[],payouts:[],events:[],audit:[],gasWei:"0",reconResidual:"0",nonce:41,approvalSeq:0};audit(s,"system","RAIL_INITIALIZED","rail:5042002");event(s,"SYSTEM","Control room ready","Arc Testnet rail initialized; mainnet remains fail-closed","success");return s}
function st(){return g.__arcrail??(g.__arcrail=fresh())} function audit(s:any,actor:string,decision:string,ref:string){const prev=s.audit.at(-1)?.hash??"GENESIS";const seq=s.audit.length+1;s.audit.push({seq,at:now(),actor,decision,subjectRef:ref,prevHash:prev,hash:h(seq+"|"+actor+"|"+decision+"|"+ref+"|"+prev)})} function event(s:any,kind:string,title:string,detail:string,status="info"){s.events.unshift({id:id("evt"),at:now(),kind,title,detail,status});s.events=s.events.slice(0,80)}
export function snapshot(){const s=st();return {...s,stats:{inbound:s.inbound.length,payouts:s.payouts.length,cases:s.inbound.filter((x:any)=>x.caseId).length,audit:s.audit.length},chain:{chainId:5042002,name:"Arc Testnet",rpc:"https://rpc.testnet.arc.io",explorer:"https://explorer.testnet.arc.io"}}}
export async function action(type:string,p:any={}){const s=st();if(type==="reset"){g.__arcrail=fresh();return snapshot()}
if(type==="inbound.create"){const x={id:id("in"),from:addr(p.from||"customer"),to:addr("collection"),amount:String(p.amount||1250),state:"DETECTED" as In,caseId:null};s.inbound.unshift(x);audit(s,"adapter","CREDIT_CANDIDATE","in:"+x.id);event(s,"INBOUND","Inbound transfer detected",x.amount+" USDC");return snapshot()}
if(type==="inbound.step"){const x=s.inbound.find((z:any)=>z.id===p.id);if(!x)throw Error("Inbound not found");const f=["DETECTED","RECEIVED","SCREENING","AWAITING_SCREENING","AVAILABLE"];const i=f.indexOf(x.state);if(i>=0)x.state=f[i+1];if(x.state==="AVAILABLE"){audit(s,"adapter","AVAILABLE","in:"+x.id);event(s,"INBOUND","Funds available",x.amount+" USDC released","success")}return snapshot()}
if(type==="inbound.quarantine"){const x=s.inbound.find((z:any)=>z.id===p.id);if(x){x.state="QUARANTINED";x.caseId=id("case");audit(s,"compliance","QUARANTINE","in:"+x.id);event(s,"CASE","Inbound quarantined","Manual case "+x.caseId,"warning")}return snapshot()}
if(type==="payout.create"){const x={id:id("out"),destination:p.destination||addr("beneficiary"),amount:String(p.amount||850),state:"ACCEPTED" as Out,policy:"PENDING",compliance:"PENDING",approval:null,txHash:null};s.payouts.unshift(x);audit(s,"cbs","PAYOUT_ACCEPTED","out:"+x.id);event(s,"PAYOUT","Instruction accepted",x.amount+" USDC");return snapshot()}
if(type==="payout.step"){const x=s.payouts.find((z:any)=>z.id===p.id);if(!x)throw Error("Payout not found");const f=["ACCEPTED","RESERVED","SCREENING","TRAVEL_RULE","SIMULATING","AWAITING_APPROVAL","APPROVED","SIGNED","BROADCAST","SETTLED"];const i=f.indexOf(x.state);if(i>=0)x.state=f[i+1];if(x.state==="RESERVED"){x.policy="ALLOW";audit(s,"policy","ALLOW","out:"+x.id)}if(x.state==="SCREENING")x.compliance="CLEAR";if(x.state==="AWAITING_APPROVAL"){s.approvalSeq++;x.approval="appr_"+s.approvalSeq;event(s,"APPROVAL","Checker approval requested","Two-person control required","warning")}if(x.state==="APPROVED")audit(s,"checker","APPROVED","out:"+x.id);if(x.state==="SIGNED"){s.nonce++;x.txHash="0x"+h(x.id+Date.now()).slice(0,64);audit(s,"signer","SIGNED","out:"+x.id)}if(x.state==="SETTLED"){audit(s,"adapter","SETTLED","out:"+x.id);event(s,"PAYOUT","Payout settled",x.amount+" USDC on Arc Testnet","success")}return snapshot()}
if(type==="payout.reject"){const x=s.payouts.find((z:any)=>z.id===p.id);if(x){x.state="HELD_FOR_CASE";audit(s,"checker","APPROVAL_REJECTED","out:"+x.id);event(s,"CASE","Payout held","No signature produced","danger")}return snapshot()}
if(type==="policy.test"){const a=Number(p.amount||1000);let decision="ALLOW",reason="Within deterministic rail limits";if(a<=0){decision="DENY";reason="ZERO_AMOUNT"}else if(a>50000){decision="DENY";reason="PER_TX_LIMIT"}else if(p.crossBorder){decision="DENY";reason="CROSS_BORDER_DISABLED"}audit(s,"policy",decision,"policy:simulation");event(s,"POLICY","Policy "+decision,a+" USDC · "+reason,decision==="ALLOW"?"success":"warning");return {decision,reason,...snapshot()}}
if(type==="compliance.screen"){const v=/dead|bad|sanction|^0x0+$/i.test(String(p.address||""))?"HIT":"CLEAR";audit(s,"compliance","SCREEN_"+v,"address");event(s,"COMPLIANCE","Address "+v,v==="HIT"?"Demo blocklist match":"No demo blocklist match",v==="HIT"?"danger":"success");return {verdict:v,...snapshot()}}
if(type==="recon.run"){s.reconResidual=p.drift?"0.000001":"0";if(s.reconResidual!=="0"){s.rail="PAUSED";audit(s,"reconciler","PAUSE_RECON_DRIFT","recon:current");event(s,"RECON","Zero-tolerance drift detected","Circuit breaker paused the rail","danger")}else event(s,"RECON","Reconciliation clean","Chain ↔ adapter ↔ CBS residual = 0","success");return snapshot()}
if(type==="rail.unpause"){if(!p.a||!p.b||p.a===p.b)throw Error("Two distinct approvers are required");s.rail="RUNNING";audit(s,"two-person","UNPAUSE","rail:current");event(s,"RECON","Rail unpaused","Two distinct approvers supplied","success");return snapshot()}
if(type==="audit.verify"){const ok=s.audit.every((x:any,i:number)=>i===0?x.prevHash==="GENESIS":x.prevHash===s.audit[i-1].hash);return {ok,...snapshot()}}
throw Error("Unknown action: "+type)}