/**
 * Test support: two structurally different in-memory PayoutPartnerPort fakes (§7.8).
 * No real partner is assumed (Q-N12), so the fakes define their own test-only
 * callback scheme: header `x-fake-signature: sha256=<hex>` = HMAC-SHA256 over
 * the raw body, with a secret the test generates at run time (never stored).
 * The body is UTF-8 JSON `{"payoutId","state","reason"}`.
 *
 * - ImmediatePayout: Maps; a payout is PENDING when created and PAID on the
 *   first poll.
 * - AsyncCallbackPayout: an append-only event list; a payout stays PENDING
 *   until a signed callback is injected (`inject`), which is verified exactly
 *   like verifyCallback before it changes anything.
 *
 * Both refuse an unknown beneficiary (BENEFICIARY_INVALID) and unfunded
 * payouts (NOT_FUNDED), replay a key, can inject AMBIGUOUS, and pass the same
 * contract tests (test/contract/ports-payout.contract.test.ts).
 */
import { createHmac, timingSafeEqual } from 'node:crypto';
import { ok, rejected } from '../ids.js';
import type { BeneficiaryRef, Hex32, IdempotencyKey, PortResult } from '../ids.js';
import { canonicalPayout, payoutDedupeKey } from '../payout.js';
import type { CallbackRejectCode, CreatePayoutRejectCode, PayoutPartnerPort, PayoutRequest, PayoutState, PayoutStatus } from '../payout.js';
import { afterCommit, faultBefore } from './faults.js';
import type { FaultPlan } from './faults.js';

export const FAKE_SIGNATURE_HEADER = 'x-fake-signature';

/** Test helper: the signed raw body and headers of a callback. */
export function signFakeCallback(secret: Uint8Array, body: { readonly payoutId: string; readonly state: PayoutState; readonly reason: string | null }): { readonly rawBody: Uint8Array; readonly headers: Readonly<Record<string, string>> } {
  const rawBody = new TextEncoder().encode(JSON.stringify(body));
  return { rawBody, headers: { [FAKE_SIGNATURE_HEADER]: `sha256=${createHmac('sha256', secret).update(rawBody).digest('hex')}` } };
}

const SIG_RE = /^sha256=([0-9a-f]{64})$/;
const RANK: Readonly<Record<PayoutState, bigint>> = { PENDING: 0n, PAID: 1n, FAILED: 1n };

/** Verifies a fake callback; returns the parsed body or the refusal. `current` is the payout's known state (null: unknown payout). */
function verifyFake(
  secret: Uint8Array,
  rawBody: Uint8Array,
  headers: Readonly<Record<string, string>>,
  current: (payoutId: string) => PayoutState | null,
): PortResult<{ readonly payoutId: string; readonly state: PayoutState; readonly reason: string | null }, CallbackRejectCode> {
  const m = SIG_RE.exec(headers[FAKE_SIGNATURE_HEADER] ?? '');
  if (m === null) return rejected('BAD_SIGNATURE', 'missing or malformed signature header');
  const want = createHmac('sha256', secret).update(rawBody).digest();
  if (!timingSafeEqual(want, Buffer.from(m[1] as string, 'hex'))) return rejected('BAD_SIGNATURE', 'HMAC mismatch');
  let body: { payoutId?: unknown; state?: unknown; reason?: unknown };
  try {
    body = JSON.parse(new TextDecoder().decode(rawBody)) as typeof body;
  } catch {
    return rejected('BAD_SIGNATURE', 'body is not JSON');
  }
  const { payoutId, state, reason } = body;
  if (typeof payoutId !== 'string' || (state !== 'PENDING' && state !== 'PAID' && state !== 'FAILED') || !(reason === null || typeof reason === 'string')) {
    return rejected('BAD_SIGNATURE', 'body is not a payout callback');
  }
  const known = current(payoutId);
  if (known === null) return rejected('BAD_SIGNATURE', `unknown payout ${payoutId}`);
  if (RANK[state] < RANK[known]) return rejected('STALE', `${state} after ${known}`);
  return ok({ payoutId, state, reason }, false);
}

export interface PayoutFakeConfig {
  /** HMAC secret generated by the test at run time. */
  readonly secret: Uint8Array;
  readonly beneficiaries: readonly BeneficiaryRef[];
  readonly faults?: FaultPlan;
}

/** The shared createPayout decision: replay or key conflict, beneficiary, funding. Null: create it. */
function decideCreatePayout(
  key: IdempotencyKey,
  req: PayoutRequest,
  prior: { readonly canonical: string; readonly payoutId: string } | null,
  cfg: PayoutFakeConfig,
  funded: (txHash: Hex32) => boolean,
): PortResult<{ readonly payoutId: string }, CreatePayoutRejectCode> | null {
  if (req.amount <= 0n) throw new TypeError('a payout amount must be > 0');
  if (prior !== null) return prior.canonical === canonicalPayout(req) ? ok({ payoutId: prior.payoutId }, true) : rejected('KEY_CONFLICT', `key ${key} reused with another payout`);
  if (!cfg.beneficiaries.includes(req.beneficiaryRef)) return rejected('BENEFICIARY_INVALID', req.beneficiaryRef);
  if (!funded(req.funding.txHash)) return rejected('NOT_FUNDED', req.funding.txHash);
  return null;
}

/** Fake A: Maps; PAID on the first poll. */
export class ImmediatePayout implements PayoutPartnerPort {
  readonly #cfg: PayoutFakeConfig;
  readonly #byKey = new Map<string, { readonly canonical: string; readonly payoutId: string }>();
  readonly #state = new Map<string, PayoutState>();
  readonly #funded = new Set<string>();
  #seq = 0n;

  constructor(cfg: PayoutFakeConfig) {
    this.#cfg = cfg;
  }

  /** Test hook: the Arc funding transaction to the partner is confirmed. */
  markFunded(txHash: Hex32): void {
    this.#funded.add(txHash);
  }

  async createPayout(key: IdempotencyKey, req: PayoutRequest): Promise<PortResult<{ readonly payoutId: string }, CreatePayoutRejectCode>> {
    const before = faultBefore(this.#cfg.faults, 'createPayout');
    if (before !== null) return before;
    const refused = decideCreatePayout(key, req, this.#byKey.get(key) ?? null, this.#cfg, (h) => this.#funded.has(h));
    if (refused !== null) return refused;
    this.#seq += 1n;
    const payoutId = `ip-${this.#seq}`;
    this.#byKey.set(key, { canonical: canonicalPayout(req), payoutId });
    this.#state.set(payoutId, 'PENDING');
    return afterCommit(this.#cfg.faults, 'createPayout', ok({ payoutId }, false));
  }

  async getPayout(payoutId: string): Promise<PortResult<PayoutStatus, 'NOT_FOUND'>> {
    const before = faultBefore(this.#cfg.faults, 'getPayout');
    if (before !== null) return before;
    if (!this.#state.has(payoutId)) return rejected('NOT_FOUND', payoutId);
    this.#state.set(payoutId, 'PAID');
    return ok({ state: 'PAID', reason: null }, false);
  }

  verifyCallback(rawBody: Uint8Array, headers: Readonly<Record<string, string>>): PortResult<{ readonly dedupeKey: string }, CallbackRejectCode> {
    const v = verifyFake(this.#cfg.secret, rawBody, headers, (id) => this.#state.get(id) ?? null);
    return v.kind === 'OK' ? ok({ dedupeKey: payoutDedupeKey(v.value.payoutId, v.value.state) }, false) : v;
  }
}

type PayoutEvent =
  | { readonly type: 'CREATED'; readonly key: IdempotencyKey; readonly canonical: string; readonly payoutId: string }
  | { readonly type: 'FUNDED'; readonly txHash: Hex32 }
  | { readonly type: 'STATE'; readonly payoutId: string; readonly state: PayoutState; readonly reason: string | null };

/** Fake B: an event list; PENDING until a verified callback is injected. */
export class AsyncCallbackPayout implements PayoutPartnerPort {
  readonly #cfg: PayoutFakeConfig;
  #events: readonly PayoutEvent[] = [];

  constructor(cfg: PayoutFakeConfig) {
    this.#cfg = cfg;
  }

  markFunded(txHash: Hex32): void {
    this.#events = [...this.#events, { type: 'FUNDED', txHash }];
  }

  #status(payoutId: string): PayoutStatus | null {
    let s: PayoutStatus | null = null;
    for (const e of this.#events) {
      if (e.type === 'CREATED' && e.payoutId === payoutId) s = { state: 'PENDING', reason: null };
      if (e.type === 'STATE' && e.payoutId === payoutId) s = { state: e.state, reason: e.reason };
    }
    return s;
  }

  /** Test hook: the partner's callback arrives; applied only if it verifies. */
  inject(rawBody: Uint8Array, headers: Readonly<Record<string, string>>): PortResult<{ readonly dedupeKey: string }, CallbackRejectCode> {
    const v = verifyFake(this.#cfg.secret, rawBody, headers, (id) => this.#status(id)?.state ?? null);
    if (v.kind !== 'OK') return v;
    this.#events = [...this.#events, { type: 'STATE', ...v.value }];
    return ok({ dedupeKey: payoutDedupeKey(v.value.payoutId, v.value.state) }, false);
  }

  async createPayout(key: IdempotencyKey, req: PayoutRequest): Promise<PortResult<{ readonly payoutId: string }, CreatePayoutRejectCode>> {
    const before = faultBefore(this.#cfg.faults, 'createPayout');
    if (before !== null) return before;
    const prior = this.#events.find((e) => e.type === 'CREATED' && e.key === key);
    const refused = decideCreatePayout(key, req, prior?.type === 'CREATED' ? prior : null, this.#cfg, (h) => this.#events.some((e) => e.type === 'FUNDED' && e.txHash === h));
    if (refused !== null) return refused;
    const payoutId = `ap-${key}`;
    this.#events = [...this.#events, { type: 'CREATED', key, canonical: canonicalPayout(req), payoutId }];
    return afterCommit(this.#cfg.faults, 'createPayout', ok({ payoutId }, false));
  }

  async getPayout(payoutId: string): Promise<PortResult<PayoutStatus, 'NOT_FOUND'>> {
    const before = faultBefore(this.#cfg.faults, 'getPayout');
    if (before !== null) return before;
    const s = this.#status(payoutId);
    return s === null ? rejected('NOT_FOUND', payoutId) : ok(s, false);
  }

  verifyCallback(rawBody: Uint8Array, headers: Readonly<Record<string, string>>): PortResult<{ readonly dedupeKey: string }, CallbackRejectCode> {
    const v = verifyFake(this.#cfg.secret, rawBody, headers, (id) => this.#status(id)?.state ?? null);
    return v.kind === 'OK' ? ok({ dedupeKey: payoutDedupeKey(v.value.payoutId, v.value.state) }, false) : v;
  }
}
