/**
 * FAKE PAYOUT PARTNER: for tests and the testnet demo only. NOT a real partner,
 * and not CPN-shaped: it exists so the shared contract tests run against a
 * structurally different adapter than the CPN stub.
 *
 * Wire format (ours, invented for the fake; nothing here is a CPN or partner
 * field): the body is a JSON object `{eventId, payoutId, state, reason}`, and
 * the header `x-fake-partner-signature` carries the lower-case hex
 * HMAC-SHA256 of the raw body under a secret injected at construction (tests
 * generate a throwaway one at runtime; no secret lives in the repo). The
 * comparison is constant time and runs over the raw bytes.
 */
import { createHmac, timingSafeEqual } from 'node:crypto';
import { optString, reqString } from '../../../dfns/json.js';
import { ok, rejected } from '../../../nova-ports/ids.js';
import type { PortResult } from '../../../nova-ports/ids.js';
import { PartnerCore, decodeBodyObject, headerValue } from './core.js';
import type { PartnerCoreOptions } from './core.js';
import type { CallbackRejectCode, PartnerCallback, PartnerPayoutState } from './port.js';

export const FAKE_SIGNATURE_HEADER = 'x-fake-partner-signature';
/** At least 16 bytes. */
const SECRET_HEX = /^(?:[0-9a-f]{2}){16,}$/;
const HEX64 = /^[0-9a-f]{64}$/;
const STATES: readonly string[] = ['PENDING', 'PAID', 'FAILED', 'RETURNED', 'REFUND_FAILED'];

/** Signs a callback body the way the fake partner does (test helper). */
export function fakePartnerSign(secret: Uint8Array, rawBody: Uint8Array): string {
  return createHmac('sha256', secret).update(rawBody).digest('hex');
}

export interface FakePartnerOptions extends PartnerCoreOptions {
  /** Callback HMAC secret, at least 16 bytes; generated by the caller at runtime. */
  readonly secret: Uint8Array;
}

export class FakePartner extends PartnerCore {
  readonly kind = 'FAKE_PARTNER' as const;
  readonly #secret: Uint8Array;

  constructor(o: FakePartnerOptions) {
    super(o);
    if (!SECRET_HEX.test(Buffer.from(o.secret).toString('hex'))) throw new RangeError('secret too short');
    this.#secret = Uint8Array.from(o.secret);
  }

  protected formatId(token: string): string {
    return `fake-${token}`;
  }

  verifyCallback(rawBody: Uint8Array, headers: Readonly<Record<string, string>>): PortResult<PartnerCallback, CallbackRejectCode> {
    const given = headerValue(headers, FAKE_SIGNATURE_HEADER);
    if (given === null || !HEX64.test(given)) return rejected('BAD_SIGNATURE', 'signature missing or malformed');
    const want = Buffer.from(fakePartnerSign(this.#secret, rawBody), 'hex');
    if (!timingSafeEqual(want, Buffer.from(given, 'hex'))) return rejected('BAD_SIGNATURE', 'signature mismatch');
    const o = decodeBodyObject(rawBody);
    if (o === null) return rejected('MALFORMED', 'body is not a JSON object');
    try {
      const state = reqString(o, 'state');
      if (!STATES.includes(state)) return rejected('MALFORMED', 'unknown state');
      return ok(
        {
          eventId: reqString(o, 'eventId', /^[\x21-\x7e]{1,128}$/),
          payoutId: reqString(o, 'payoutId', /^[\x21-\x7e]{1,128}$/),
          state: state as PartnerPayoutState,
          reason: optString(o, 'reason'),
        },
        false,
      );
    } catch {
      return rejected('MALFORMED', 'callback fields missing or invalid');
    }
  }
}
