#!/usr/bin/env python3
"""Shared source-drift check for docs/sources/MANIFEST.md (stdlib only, read-only).

For every archived file listed in MANIFEST:
  1. recompute its SHA-256 and compare it with the MANIFEST value (archive integrity);
  2. re-fetch the live URL and compare its bytes with the NEWEST archive of that URL (drift).

Verifiers cite the report this writes, instead of each re-fetching every page.
It never edits archives (MANIFEST rule 2). Exit status: 0 clean, 1 drift or integrity
failure, 2 fetch errors only.

Usage: python3 tools/source_drift.py [--out docs/verification/source-drift-YYYY-MM-DD.md]
"""
import datetime
import difflib
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MANIFEST = DOCS / "sources" / "MANIFEST.md"
ROW = re.compile(r"^\| `([^`]+)` \| (\S+)[^|]*\| ([^|]+) \| `([0-9a-f]{64})` \|")


def sha256(b):
    return hashlib.sha256(b).hexdigest()


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "arc-rail-source-drift/1"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.status, r.read()


def main():
    out = None
    if "--out" in sys.argv:
        out = Path(sys.argv[sys.argv.index("--out") + 1])
    rows = []
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        m = ROW.match(line)
        if m:
            rows.append(dict(file=m.group(1), url=m.group(2), fetched=m.group(3).strip(), sha=m.group(4)))

    lines, integrity_fail, drift, errors = [], 0, 0, 0
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f"# Source drift report, {now}\n")
    lines.append(f"Generated by `tools/source_drift.py` from `docs/sources/MANIFEST.md` ({len(rows)} archived files).\n")

    lines.append("## 1. Archive integrity (recomputed SHA-256 vs MANIFEST)\n")
    lines.append("| File | Result |\n|---|---|")
    for r in rows:
        p = DOCS / r["file"]
        if not p.exists():
            res, integrity_fail = "**MISSING**", integrity_fail + 1
        else:
            got = sha256(p.read_bytes())
            ok = got == r["sha"]
            res = "match" if ok else f"**MISMATCH** (got `{got}`)"
            integrity_fail += 0 if ok else 1
        lines.append(f"| `{r['file']}` | {res} |")

    # newest archive per URL (MANIFEST 'Fetched' strings sort chronologically: YYYY-MM-DD HH:MM UTC)
    newest = {}
    for r in rows:
        if r["url"].startswith("http") and (r["url"] not in newest or r["fetched"] > newest[r["url"]]["fetched"]):
            newest[r["url"]] = r

    lines.append("\n## 2. Live drift (live bytes vs newest archive of each URL)\n")
    lines.append("| URL | Newest archive | Result |\n|---|---|---|")
    details = []
    for url, r in sorted(newest.items()):
        try:
            status, live = fetch(url)
        except Exception as e:  # report, never guess
            errors += 1
            lines.append(f"| {url} | `{r['file']}` | **FETCH ERROR**: {type(e).__name__}: {e} |")
            continue
        arch = (DOCS / r["file"]).read_bytes() if (DOCS / r["file"]).exists() else b""
        if live == arch:
            lines.append(f"| {url} | `{r['file']}` | identical (HTTP {status}) |")
            continue
        drift += 1
        a = arch.decode("utf-8", "replace").splitlines()
        b = live.decode("utf-8", "replace").splitlines()
        diff = list(difflib.unified_diff(a, b, "archive", "live", n=0, lineterm=""))
        removed = sum(1 for d in diff if d.startswith("-") and not d.startswith("---"))
        added = sum(1 for d in diff if d.startswith("+") and not d.startswith("+++"))
        lines.append(f"| {url} | `{r['file']}` | **DRIFT**: −{removed} / +{added} lines (live sha `{sha256(live)[:16]}…`) |")
        details.append(f"### {url}\n\n```diff\n" + "\n".join(diff[:200]) + ("\n… (truncated)" if len(diff) > 200 else "") + "\n```\n")

    if details:
        lines.append("\n## 3. Drift details (removed lines are what a quote may depend on)\n")
        lines.extend(details)
    lines.append(f"\n**Summary:** integrity failures {integrity_fail}; drifted URLs {drift}; fetch errors {errors}; URLs checked {len(newest)}.")
    report = "\n".join(lines) + "\n"
    if out:
        out.write_text(report, encoding="utf-8")
        print(f"wrote {out}")
    print(lines[-1])
    sys.exit(1 if (integrity_fail or drift) else (2 if errors else 0))


if __name__ == "__main__":
    main()
